name: Generate terraform docs
on:
  - pull_request:
      types: [closed]

jobs:
  docs:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: ./modules
          config-file: .terraform-docs.yaml
          git-push: true
